site_name: Learn You A Haskell for Great Good!
site_description: A beginner's guide to Haskell programming language.
site_author: Miran LipovaÄa
copyright: Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License
nav:
  - Index: index.md
  - Page 1: page1.md
  - Page Group:
    - Sub Page 1: subpage/page1.md
    - Sub Page 2: subpage/page2.md
  - About: about.md
